name: CI-CD Login App

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Basic Test
        run: |
          echo "Running tests..."
          python -c "print('Test Passed')"

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Step
        run: echo "Deploying application..."
